modified 0000-01-11-gaadevyshnav.mdv1.0
githubschool/frosty pull request #24
Opened 2018-12-04 16:41 UTC by gaadevyshnav

Added caption

2018-12-04 16:44 UTC, a-a-ron commented
Hi, this looks great!

2018-12-04 16:46 UTC, a-a-ron commented on _posts/0000-01-11-gaadevyshnav.md
> +Initial commit
Nice caption

2018-12-04 16:46 UTC, ssuryaextr commented on _posts/0000-01-11-gaadevyshnav.md
> -Caption here
Nice!

2018-12-04 16:47 UTC, a-a-ron requested changes
This looks great, but let's update the title on line 3 to say something different.

2018-12-04 16:52 UTC, ssuryaextr approved these changes
Looks good.

2018-12-04 16:54 UTC, a-a-ron approved these changes

2018-12-04 16:54 UTC, merged

2018-12-05 22:43 UTC, osuvankulov commented on _posts/0000-01-11-gaadevyshnav.md
> +title: "Updated title!"
looks good